ftp download corrections
silexlabs/Silex pull request #1614
Opened 2024-09-16 08:14 UTC by oliviermgx

some ftp connector bug fixed

2024-09-23 12:28 UTC, lexoyo requested changes

2024-09-23 12:28 UTC, lexoyo commented on src/ts/plugins/server/FtpConnector.ts
> +      //const lastMod = await ftp.lastMod(folder)
you can remove this

2024-09-24 17:06 UTC, oliviermgx commented on src/ts/plugins/server/FtpConnector.ts
> +        createdAt: new Date(NaN),
remove createdAt and updateAt and add them as optional properties in WebsiteMeta type.ts

2024-09-24 17:06 UTC, oliviermgx commented on src/ts/plugins/server/FtpConnector.ts
> +      //const lastMod = await ftp.lastMod(folder)
done

2024-09-25 08:18 UTC, lexoyo approved these changes

2024-09-25 08:18 UTC, merged